import HeaderGeneric from '@/components/common/headerGenric'
import styles from './page.module.scss'
import { Metadata } from 'next'


export const metadata:Metadata = {
    title: "One Bit Flix - Login",
    description: "Generated by create next app",
}


const Login = function () {

    return (
        <>
            <main>
                <HeaderGeneric logoUrl="/" btnUrl="/register" btnContent="Quero fazer cadastro"/>
            </main>
        </>
    )
}

export default Login