import Head from "next/head";
import styles from "./page.module.scss";
import HeaderNoAuth from "@/components/homeNoAuth/headerNoAuth";
import PresentationSection from "@/components/homeNoAuth/presentationSection";
import CardSection from "@/components/homeNoAuth/cardSection";
import SlideSection from "../components/homeNoAuth/slideSection/index";
import { courseService } from "@/service/courseService";


const HomeNoAuth = async () =>{

  const newestCourses = await courseService.getNewestCourses();
  
  return (
    <>
      <Head>
        <title>OneBitFlix</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="./icon.ico" />
      </Head>
      <main>
        <div className={styles.sectionBg}>
          <HeaderNoAuth/>
          <PresentationSection/>
        </div>
        <CardSection/>
        <SlideSection newestCourses={newestCourses}/>
      </main>
    </>
  );
};


export default HomeNoAuth