import Head from "next/head";
import styles from "./page.module.scss";
const HomeNoAuth = () =>{

  return (
    <>
      <Head>
        <title>OneBitFlix</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>Home</h1>
      </main>
    </>
  );
}

export default HomeNoAuth